config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#index'

  match ':controller(/:action(/:id))', :via => [:get, :post]
  









end

app/models/cafe.rb
class Cafe < ActiveRecord::Base
	
	belongs_to :user
    
    has_many :comments
    has_many :tags
    has_many :payments
    has_many :payinfos
    mount_uploader :image,CafeimageuploaderUploader
    mount_uploader :thumnail,CafeimageuploaderUploader

    geocoded_by :address
    after_validation :geocode
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    
    belongs_to :cafe
    belongs_to :user
    
    mount_uploader :image,CafeimageuploaderUploader
end

app/models/payinfo.rb
class Payinfo < ActiveRecord::Base
	belongs_to :user
	belongs_to :cafe
end

app/models/payment.rb
class Payment < ActiveRecord::Base
    
    belongs_to :cafe
    
end

app/models/tag.rb
class Tag < ActiveRecord::Base
    belongs_to :cafe
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :caves
  has_many :comments
  has_many :payinfos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/cafe_controller.rb
class CafeController < ApplicationController
	
  def cafesearch
    @caves = Cafe.all
  end

  def cafedetail
    @cafe = Cafe.where(:cafehash => params[:hash]).take
    @hash = params[:hash]
    # @comments = @cafe.comments
  end
  
  def cafecreate

    cafe = Cafe.new
    
    cafe.name = params[:cafename]
    cafe.thumnail = params[:thumbnail]
    cafe.image = params[:cafeimage]
    cafe.signaturemenu = params[:signaturemenu]
    cafe.introduction = params[:intro_detail]
    cafe.cafehash = SecureRandom.hex(11)
    cafe.user_id = current_user.id

    cafe.address_road = params[:buyer_addr] + " " + params[:address_detail]
    cafe.address = params[:address_jibun]
    cafe.latitude = params[:latitude]
    cafe.longitude = params[:longitude]
    
    cafe.save

       
    payinfo = Payinfo.new
    payinfo.pay_method = params[:pay_method]
    payinfo.merchant_uid = params[:merchant_uid]
    payinfo.name = params[:name]
    payinfo.paid_amount = params[:paid_amount].to_i
    payinfo.pg_provider = params[:pg_provider]
    payinfo.pg_tid = params[:pg_tid]
    payinfo.apply_num = params[:apply_num]
    payinfo.vbank_num = params[:vbank_num]
    payinfo.vbank_name = params[:vbank_name]
    payinfo.vbank_holder = params[:vbank_holder]
    payinfo.vbank_date = params[:vbank_date]
    payinfo.user_id = params[:user_id].to_i
    payinfo.cafe_id = Cafe.last.id
    payinfo.save

    render :js => "window.location = '/cafe/show_payinfo'"

  end
  
  def caferegister
    @user = User.where(id: current_user.id).take

  end
  
  def add_comment
    
    cafe = Cafe.where(:cafehash => params[:cafehash]).take
    comment = Comment.new
    
    comment.user_id = current_user.id
    comment.content = params[:commentcontent]
    comment.image = params[:commentimage]
    comment.cafe_id = cafe.id
    comment.writtentime = DateTime.now
    comment.hashstr = SecureRandom.hex(11)
    
    comment.save
    
    redirect_to(:back)
  end
  
  def delete_comment
    comment = Comment.where(:hashstr => params[:hash]).take
    comment.destroy
    redirect_to(:back)
  end

  def show_payinfo
    @user = User.where(id: current_user.id).take
    @cafe = Cafe.where(id: current_user.id).take
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cafe_helper.rb
module CafeHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <!-- <h2>#{sentence}</h2> -->
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cafe/cafedetail.html.erb
<div class="container-fluid">
  <div class="row">
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src=<%= @cafe.image.url %> alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1><%= @cafe.name %></h1>
              <p><%= @cafe.introduction %></p>
            </div>
          </div>
        </div>
        
        <!--<% @comments.each do |c| %>
          <div class="item">
            <img class="second-slide" src="<%= c.image.url %>" alt="Second slide">
            <div class="container">
              <div class="carousel-caption">
                <h1><%= c.user.email %></h1>
                <p><%= c.content %></p>
              </div>
            </div>
          </div>
        <% end %>-->
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->
  </div>
</div>
<div class="container">
  <div class="row cafedetail-container">
    <div class="col-md-12">
      <div class="col-md-12 cafeinfo-container">
        <div class="col-md-2">
          <div class="circular">
            <img style="width:100%" src=<%= @cafe.thumnail.url %>>
          </div>
        </div>
        <div class="col-md-7">
          <p class="cafedetail-cafename">
            <span>
              <%= @cafe.name %>
            </span>
          </p>
          <p class="cafedetail-cafeaddr">
            <span>
              <%= @cafe.address %>
            </span>
          </p>
          <p class="cafedetail-cafesignature">
            <span>
            시그니처 메뉴: &nbsp; <a style="font-style:bold"><%= @cafe.signaturemenu %></a>
            </span>
          </p>
        </div>
        <div class="col-md-3">
          <div class="cafedetail-tags">
            <% @cafe.tags.each do |tag| %>
            <span class="label label-default"><%= tag.content %></span>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-12 cafeintro-container">
        <div class="col-md-12">
          <h2>카페소개</h2>
        </div>
        <div class="col-md-9 cafeintroduction">
          <%= @cafe.introduction %>
        </div>
      </div>
      <div class="col-md-12 cafereplies-container">
        <form action="/cafe/add_comment" method="POST" enctype="multipart/form-data" style="width:100%">
          
          <div class="fileinput fileinput-new" data-provides="fileinput">
            <span class="btn btn-default btn-file"><span class="fileinput-new">Select file</span><span class="fileinput-exists">Change</span><input type="file" name="..."></span>
            <span class="fileinput-filename"></span>
            <a href="#" class="close fileinput-exists" data-dismiss="fileinput" style="float: none">&times;</a>
          </div>
          
          <div class="each-form-single-line form-group form-group-lg">
            <h3>로고 사진</h3>
            <input type="file" name="thumbnail" accept="image/*">
          </div>
          <!-- <input type="file" name="commentimage" accept="image/*"> -->
          <input type="hidden" name="cafehash" value="<%= @cafe.cafehash %>">
          <div class="col-md-8 cafecomment-content">
            <textarea name="commentcontent"></textarea>  
          </div>
          <div class="col-md-2">
            <input class="btn btn-default pull-left" type="submit" value="코멘트추가">
          </div>
        </form>
      </div>
      <div class="col-md-12 commentview-container">
        <% @comments.each do |c| %>
        <div class="col-md-10" style="border-bottom : 1px solid #DDDDDD">
          <div style="margin-top:5px margin-bottom:3px">
            <span><%= c.user.email %></span>
            <span class="pull-right"><%= c.writtentime.to_s[0,16] %></span>
          </div>
          <div style="margin-bottom:5px">
            <span class="glyphicon glyphicon-arrow-right"></span><span><%= c.content %></span>
            <% if c.user.id.nil? && c.user.id == current_user.id %>
              <%= link_to "삭제하기", :action => 'delete_comment', :controller => 'cafe', :hash => c.hashstr %>
            <% end %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    
  </div>
</div>


app/views/cafe/caferegister.erb
<div class="container bucket-container">
 <div  class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
  <div>
    <h1 class="headline text-weight_300">
       카페 등록하기
    </h1>
  </div>
      <form accept-charset="UTF-8" action="/cafe/cafecreate" class="new_project_request text-left" id="new_project_request" enctype="multipart/form-data" method="post" name="frm_payment">
          <div class="each-form-single-line form-group form-group-lg">
            <h3>카페 이름</h3>
              <input class="form-control input-lg" type="text" placeholder="Cafe's name" name="cafename" id = "cafename" value="<%= @title %>" required><br>
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>카페 주소</h3>
              <!-- <input class="form-control input-lg" type="text" placeholder="Cafe's address" name="address" value="" required><br> -->
            <div class="postnumber input-group input-group-lg col-md-4 col-md-offset-0" id="home-input-group">
              <input id="postcode" type="text" class="form-control" style="padding:5px; text-align:center" placeholder="우편번호" name="buyer_postcode" readonly="true">
              <span class="input-group-btn">
                <a class="btn btn-danger" onclick="execDaumPostcode()" type="submit">검색</a>
              </span>
            </div>
            <br>
            <input class="form-control input-lg" name = "buyer_addr" type="text" id="address" placeholder="주소" readonly="true"><br>
            <input class="form-control input-lg" name = "address_detail" type="text" id="address_detail" placeholder="상세주소">
            <input type="hidden" name = "address_jibun" id="jibunAddress" placeholder="지번주소">
            <!-- <input type="submit" value="저장" %> -->
            
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>대표 메뉴</h3>
              <input class="form-control input-lg" type="text" placeholder="Cafe's signature" name="signaturemenu" id="signaturemenu" required><br>
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>로고 사진</h3>
              <input type="file" name="thumbnail" id ="thumbnail"accept="image/*">
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>대표 사진</h3>
              <input type="file" name="cafeimage" id="cafeimage" accept="image/*">
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>카페 소개</h3>
                <textarea class="form-control" rows="11" placeholder="Introduce your bucket" name="intro_detail" id ="intro_detail" required></textarea>
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>카페 태그</h3>
            <span>태그를 달아주세요 (ex 라떼, 에스프레소, 케익)</span>
              <input class="form-control input-lg" type="text" placeholder="tag1" name="tag1" value="" required><br>
              <input class="form-control input-lg" type="text" placeholder="tag2" name="tag2" value="" required><br>
              <input class="form-control input-lg" type="text" placeholder="tag3" name="tag3" value="" required><br>
          </div>
          <div class="each-form-single-line form-group form-group-lg">
            <h3>결제 수단</h3>
            <span>생성하기 버튼을 누르고 결제를 하셔야 카페등록이 완료됩니다.</span>
            <select name="pay_method" id="pay_method" class="form-control input-lg">
              <option value="card">신용카드</option>
              <option value="trans">실시간계좌이체</option>
              <option value="vbank">가상계좌</option>
              <option value="phone">휴대폰소액결제</option>
            </select>
            <input type="checkbox" name="use_escrow" value="escrow" id="use_escrow">
            <span id="escrow-label"> 에스크로결제적용</span>
            <input type="hidden" name="merchant_uid" id="merchant_uid" value="">
            <input type="hidden" name="name" id="name" value="결제테스트">
            <input type="hidden" name="amount" id="amount" value="1000">
            <input type="hidden" name="buyer_email" id="buyer_email" value="<%= @user.email %>">
            <input type="hidden" name="buyer_name" id="buyer_name" value="cheon">
            <input type="hidden" name="buyer_tel" id="buyer_tel" value="070-8658-8870">
            <input type="hidden" name="vbank_due" id="vbank_due" value="">
            <input type="hidden" id="user_id" value = "<%= @user.id %>">       
          </div>          
          <div>
            <input class="btn btn-primary btn-lg col-xs-12 col-sm-12 col-md-12 col-lg-12" type="submit" value="생성하기" id="submit_button">
          </div>
      </form> 
    </div>
  </div>
</div>

<script type="text/javascript" src="/js/moment.min.js"></script>
<script type="text/javascript">
function callback() {
    //loaded
    $(function() {
        document.frm_payment.merchant_uid.value = 'merchant_' + new Date().getTime();
        document.frm_payment.vbank_due.value = moment().add(2, 'day').format('YYYYMMDD');

        $('#submit_button').click(function() {
            var frm = document.frm_payment;
            var IMP = window.IMP;
            var escrow = $(frm.use_escrow).is(':checked')
            IMP.init('imp79476461');
            IMP.request_pay({
                pay_method : frm.pay_method.value,
                escrow : escrow,
                merchant_uid : frm.merchant_uid.value,
                name:frm.name.value, 
                amount:frm.amount.value, 
                buyer_email:frm.buyer_email.value, 
                buyer_name:frm.buyer_name.value, 
                buyer_tel:frm.buyer_tel.value, 
                buyer_addr:frm.buyer_addr.value,
                buyer_postcode:frm.buyer_postcode.value,
                vbank_due:frm.vbank_due.value,
                app_scheme:'iamporttest'
            }, function(rsp) {
                if ( rsp.success ) {
                    var msg = '결제가 완료되었습니다.<br>';
                    msg += '고유ID : ' + rsp.imp_uid + '<br>';
                    msg += '상점 거래ID : ' + rsp.merchant_uid + '<br>';
                    msg += '결제 금액 : ' + rsp.paid_amount + '<br>';

                    if ( rsp.pay_method === 'card' ) {
                        msg += '카드 승인번호 : ' + rsp.apply_num + '<br>';
                    } else if ( rsp.pay_method === 'vbank' ) {
                        msg += '가상계좌 번호 : ' + rsp.vbank_num + '<br>';
                        msg += '가상계좌 은행 : ' + rsp.vbank_name + '<br>';
                        msg += '가상계좌 예금주 : ' + rsp.vbank_holder + '<br>';
                        msg += '가상계좌 입금기한 : ' + rsp.vbank_date + '<br>';
                    }
                  $.ajax({
                      data: {
                              pay_method: rsp.pay_method, 
                              merchant_uid: rsp.merchant_uid,
                              name: rsp.name, 
                              paid_amount: rsp.paid_amount,
                              pg_provider: rsp.pg_provider,
                              pg_tid: rsp.pg_tid,
                              apply_num: rsp.apply_num,
                              vbank_num: rsp.vbank_num,
                              vbank_name: rsp.vbank_name,
                              vbank_holder: rsp.vbank_holder,
                              vbank_date: rsp.vbank_date,
                              user_id: $("#user_id").val(),
                              cafename: $("#cafename").val(),
                              thumbnail: $("#thumbnail").val(),
                              cafeimage: $("#cafeimage").val(),
                              signaturemenu: $("#signaturemenu").val(),
                              intro_detail: $("#intro_detail").val(),
                              buyer_addr: $("#address").val(),
                              address_detail: $("#address_detail").val(),
                              address_jibun: $("#jibunAddress").val()


                      },
                      url: '/cafe/cafecreate',
                      enctype: "multipart/form-data",
                      method: "post"
                    });
    

                } else {
                    var msg = '결제에 실패하였습니다.' + '\n';
                    msg += '에러내용 : ' + rsp.error_msg + '\n';
                    alert(msg);
                    location.href ="/cafe/caferegister/<%= @user.id %>";
                }
            });

            return false;
        });

    });
}

var script = document.createElement('script');
script.type = "text/javascript";

if ( script.readyState ) { //IE
    script.onreadystatechange = function() {
        if ( script.readyState == 'loaded' || script.readyState == 'complete' ) {
            script.onreadystatechange = null;
            callback();
        }
    }

} else {
    script.onload = function() {
        callback();
    }
}

script.src = "https://service.iamport.kr/js/iamport.payment.js";
document.getElementsByTagName('head')[0].appendChild(script);
</script>


<script type="text/javascript">
//우편번호 찾기 버튼 클릭 시
function execDaumPostcode() {
        new daum.Postcode({
            oncomplete: function(data) {
                // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.

                // 각 주소의 노출 규칙에 따라 주소를 조합한다.
                // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다.
                var fullAddr = ''; // 최종 주소 변수
                var extraAddr = ''; // 조합형 주소 변수
                var Jibun_address = '';

                // 사용자가 선택한 주소 타입에 따라 해당 주소 값을 가져온다.
                if (data.userSelectedType === 'R') { // 사용자가 도로명 주소를 선택했을 경우
                    JibunAddress = data.autoJibunAddress;

                } else { // 사용자가 지번 주소를 선택했을 경우(J)
                    JibunAddress = data.jibunAddress;
                }
                

                // 사용자가 선택한 주소가 도로명 타입일때 조합한다.
                if(data.userSelectedType === 'R'){
                    //법정동명이 있을 경우 추가한다.
                    if(data.bname !== ''){
                        extraAddr += data.bname;
                    }
                    // 건물명이 있을 경우 추가한다.
                    if(data.buildingName !== ''){
                        extraAddr += (extraAddr !== '' ? ', ' + data.buildingName : data.buildingName);
                    }
                    // 조합형주소의 유무에 따라 양쪽에 괄호를 추가하여 최종 주소를 만든다.
                    fullAddr += (extraAddr !== '' ? ' ('+ extraAddr +')' : '');
                }

                // 우편번호와 주소 정보를 해당 필드에 넣는다.
                document.getElementById('postcode').value = data.zonecode; //5자리 새우편번호 사용
                document.getElementById('address').value = data.roadAddress;
                document.getElementById('jibunAddress').value = JibunAddress;
                // 커서를 상세주소 필드로 이동한다.
                document.getElementById('address_detail').focus();
            }
        }).open();
    }
</script>


app/views/cafe/cafesearch.html.erb
<div class="container">
  <div class="row" style="border-bottom:1px solid #d9d9d9">
    <div class="top-sentence">
      <span class="topsent1">스페셜한 하루를 위해!</span><br>
      <span class="topsent2">특별해지는 경험을 해보세요.</span>
    </div>
  </div>
  <div class="row" style="transform:translateY(1%)">
    <div class="col-lg-6">
      <% @caves.each do |x| %>
        <img style="width:100px;height:100px"src="<%= x.thumnail.url %>" alt="thumnail img"><br>
        <b><%= x.name %></b><br>
        <div style="border-bottom:1px solid #d9d9d9"><%= x.address %></div><br>
      <% end %>
    </div>

    <div class="col-lg-6">
      <div id="map_canvas" style="min-height:800px;min-width:555px;">map div</div>
    </div>
  </div>
</div>

app/views/cafe/create_payinfo.erb
<input type="submit" id="dd" value="aaaaaaa">

<script type="text/javascript" src="/js/moment.min.js"></script>
<script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment.js">

</script>
<script type="text/javascript">
$(document).ready(function(){
$("#dd").click(function(){
var IMP = window.IMP; 
IMP.init('imp79476461');
IMP.request_pay({
          pay_method : 'card', // 'card':신용카드, 'trans':실시간계좌이체, 'vbank':가상계좌, 'phone':휴대폰소액결제
          merchant_uid : 'merchant_' + new Date().getTime(),
          name : '주문명:결제테스트',
          amount : 14000,
          buyer_email : 'iamport@siot.do',
          buyer_name : '구매자이름',
          buyer_tel : '070-8658-8870',
          buyer_addr : '서울특별시 강남구 삼성동',
          buyer_postcode : '123-456'
      }, function(rsp) {
          if ( rsp.success ) {
              var msg = '결제가 완료되었습니다.';
              msg += '고유ID : ' + rsp.imp_uid;
              msg += '상점 거래ID : ' + rsp.merchant_uid;
              msg += '결제 금액 : ' + rsp.paid_amount;
              msg += '카드 승인번호 : ' + rsp.apply_num;
          } else {
              var msg = '결제에 실패하였습니다.';
              msg += '에러내용 : ' + rsp.error_msg;
          }
      });
});
});

</script>

app/views/cafe/show_payinfo.erb
<div class ="container" style="text-align:center">
	<div class ="row">
		<h1>모든 결제 내역</h1>
		<% @user.payinfos.each do |p| %>
		<h6>결제수단 : <%= p.pay_method %></h6>
		<h6>merchant_uid : <%= p.merchant_uid %></h6>
		<h6>주문명 : <%= p.name %></h6>
		<h6>결제된 금액 : <%= p.paid_amount %></h6>
		<h6>PG사 이름 : <%= p.pg_provider %></h6>
		<h6>PG사 승인번호 : <%= p.pg_tid %></h6>
		<h6>카드사 승인번호(신용카드 결제일 때만 있음) : <%= p.apply_num %></h6>
		<h6>가상계좌 입금계좌번호(가상계좌 결제일 때만 있음) : <%= p.vbank_num %></h6>
		<h6>가상계좌 은행명(가상계좌 결제일 때만 있음) : <%= p.vbank_date %></h6>
		<h6>가상계좌 예금주(가상계좌 결제일 때만 있음) : <%= p.vbank_name %></h6>
		<h6>가상계좌 입금기한(가상계좌 결제일 때만 있음) : <%= p.vbank_holder %></h6>
		<h6>user_id : <%= p.user_id %></h6>
		<h6>cafe_id : <%= p.cafe_id %></h6>
		<h6>---------------------------------------------------------</h6>
		<% end %>
	</div>
</div>

app/views/home/index.html.erb
<div class="container-fluid">
  <div class="row" id="fullscreen-wrap">
    <div class="embed-responsive embed-responsive-16by9" >
      <div class="row home-introduction-sentence">
        <div class="col-md-8 col-md-offset-2">
          <h2><span>Find Your Specialty</span></h2>
          <div><span>1000개이상의 스페셜티 카페를 찾아보세요.</span></div>
        </div>
      </div>
      <iframe class="embed-responsive-item" src="//www.youtube.com/embed/zro0mJ9V7ZQ?autoplay=1&controls=0&showinfo=0&autohide=1&loop=1&playlist=lG5aSZBAuPs" autoscreen></iframe>
      <div class="row home-search-wrap">
        <form action="/pureblack/cafesearch" method="POST">
          <div class="input-group input-group-lg col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3" id="home-input-group">
            <input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
            <input type="text" class="form-control" value="오늘은 어디서 커피를 드시겠어요?" style="padding:5px; text-align:center" name="searchword">
            <span class="input-group-btn">
              <a class="btn btn-danger" type="submit" href="/cafe/cafesearch">검색</a>
            </span>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<div class="container" id="startchange">
  <div class="row">
    <div class="top-sentence">
      <span class="topsent1">스페셜한 하루를 위해!</span><br>
      <span class="topsent2">특별해지는 경험을 해보세요.</span>
    </div>
  </div>
  <div class="row content-row">
    <div class="col-md-8">
      <div class="content-img1">
        <span>가로수 길</span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-img1">
        <span>대왕커피</span>
      </div>
    </div>
  </div>
  
  <div class="row content-row">
    <div class="col-md-4">
      <div class="content-img1">
        <span>홍대</span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-img1">
        <span>홍대</span>
      </div>
    </div>
    <div class="col-md-4">
      <div class="content-img1">
        <span>홍대</span>
      </div>
    </div>
  </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <br><%= link_to "로그인하기", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <br><%= link_to "아직 아이디가 없으신가요?", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <br><%= link_to "비밀번호가 기억나지 않으세요?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>